### ISSUE TITLE
Request: Hiding password with *

### ISSUE THREAD

**Issue by purerosefallen** [GDUT-Drcom/GDUT-Drcom-Dialer#18]
It could be very annoying if my classmate is next to me while I'm working on my computer. They would see my password in plain text.
Could you please add an option to hide the password? Thanks.

**Comment by jiangming1399** [comment]
Hello, thanks for your suggestion. I will add the hiding function later, but it might require some time.

**Comment by purerosefallen** [comment]
Thanks.

**Comment by purerosefallen** [comment]
In addition, is this one possible to run on Mono? It could be one of my dream to work with my computer in my dormitory in GDUT.

**Comment by jiangming1399** [comment]
@purerosefallen Sorry, it's impossible to run this software on non-windows platfrom; if you want to connect to the school network on Ubuntu, I would recommend you use chenhaowen01/gdut-drcom , or run chenhaowen01/gdut-drcom-for-openwrt on your router.

**Comment by purerosefallen** [comment]
To tell the truth, I have tried many solutions connecting to the school network with my Ubuntu since I enter GDUT. It really made me annoyed. I dialed the Internet Center of the school for multiple times, but they replied nothing but "Our school network doesn't support Ubuntu. Please switch to another operating system."
I thought of a solution, running this project in a Windows virtual machine, connecting with bridge network, and using the Windows network sharing to share the internet connection back to my Ubuntu host machine. However, the school server cut my connection after all the procedures when trying to access the internet from Ubuntu.
Could you be so kind as to tell me, how did the original Dr.Com client detect the internet sharing? By the client, or the server? In addition, could you think of any solutions of my situation?

**Comment by lindexi** [comment]
Why do you need to hide the password? If your roommate peeks your password, you can kill him.

**Comment by lindexi** [comment]
> Hello, thanks for your suggestion. I will add the hiding function later, but it might require some time.

我记得当初讨论过不加上的一个原因是小白用户很多，输错了密码自己不知道

**Comment by lindexi** [comment]
https://github.com/GDUT-Drcom/GDUT-Drcom-Dialer/issues/2#issuecomment-267806823

**Comment by jiangming1399** [comment]
> how did the original Dr.Com client detect the internet sharing? By the client, or the server?

Both. On the client side, drcom client check your driver to determine; on the server side, server use DPI (Deep Packet Inspection) check if your data packet is send by multi device.

> In addition, could you think of any solutions of my situation?

Use Openwrt router dial, then use global proxy or something else to bypass the DPI check.

**Comment by lyhyl** [comment]
It is highly recommended to try the projects listed in the [comment](https://github.com/GDUT-Drcom/GDUT-Drcom-Dialer/issues/18#issuecomment-485730436). This project is actually a GUI wrapper of [chenhaowen01/gdut-drcom](https://github.com/chenhaowen01/gdut-drcom) only. If that project do not run properly on your Ubuntu, GDUT should be blamed.

**Comment by purerosefallen** [comment]
@lindexi Password should be considered as a personal privacy. Almost every software that contains a password input box would hide the password with character `*`.
It's obvious that some other students would visit our dormitory offering advertisements. In addition, some classmates from the neighboring room would visit us. Even though my roommates could be trusted, those students may still peek my password.
I would be so glad if you could respect the users' privacy by hiding the password with `*`.

**Comment by purerosefallen** [comment]
@lyhyl Could you tell me how to write the config file in Longdong Campus?

**Comment by lyhyl** [comment]
> @lyhyl Could you tell me how to write the config file in Longdong Campus?

The configuration is hard coded. 😂

The authentication IP is located in `Drcom-Dialer.Core/Model/DialerConfig.cs` Line 118.

and the heart beat configuration is located in `Drcom-Dialer.Core/Model/HeartBeatProxy.cs` Line 39 to 43.

**Comment by purerosefallen** [comment]
@lyhyl I further read the project and the upstream project, and realized that the dial is done by common pppoe, and an additional heartbeat would be done after connection.
However, I still have no idea how to establish the connection. I tried to use the common pppoe `sudo pon dsl-provider`, but I got this.
```
Apr 23 20:54:09 nanahira-another pppd[5719]: Remote message: userid error5
Apr 23 20:54:09 nanahira-another pppd[5719]: PAP authentication failed
Apr 23 20:54:09 nanahira-another pppd[5719]: Modem hangup
Apr 23 20:54:09 nanahira-another pppd[5719]: Connection terminated.
Apr 23 20:54:09 nanahira-another pppd[5719]: Sent PADT
```
Asking for help..

**Comment by lyhyl** [comment]
> @lyhyl I further read the project and the upstream project, and realized that the dial is done by common pppoe, and an additional heartbeat would be done after connection.
> However, I still have no idea how to establish the connection. I tried to use the common pppoe `sudo pon dsl-provider`, but I got this.
> 
> ```
> Apr 23 20:54:09 nanahira-another pppd[5719]: Remote message: userid error5
> Apr 23 20:54:09 nanahira-another pppd[5719]: PAP authentication failed
> Apr 23 20:54:09 nanahira-another pppd[5719]: Modem hangup
> Apr 23 20:54:09 nanahira-another pppd[5719]: Connection terminated.
> Apr 23 20:54:09 nanahira-another pppd[5719]: Sent PADT
> ```
> Asking for help..

I don't have much experience with cracking Drcom on Ubuntu, but I noticed that the first error says it is a user id error.

In particul, user id is not just your student id, the correct user id in the network system is `"stduent id" + "\r\n"`. For example, if your student id is `"3114001234"`, then the correct authentication user id should be `"3114001234\r\n"`. This odd behavior block the common way to dial. As far as I know, this behavior can only be done by code or powershell.

Hope this information would help you.

**Comment by jiangming1399** [comment]
Ok, the feature you requested is done. If you have other question about drcom in gdut, you could join the qq group: 279729674

**Comment by lindexi** [comment]
> @lindexi Password should be considered as a personal privacy. Almost every software that contains a password input box would hide the password with character `*`.
> It's obvious that some other students would visit our dormitory offering advertisements. In addition, some classmates from the neighboring room would visit us. Even though my roommates could be trusted, those students may still peek my password.
> I would be so glad if you could respect the users' privacy by hiding the password with `*`.

AOE 群杀
