### ISSUE TITLE
为什么监听密码更改的时候使用的是 KeyUp 而不是 PasswordChanged 事件？

### ISSUE THREAD

**Issue by lindexi** [GDUT-Drcom/GDUT-Drcom-Dialer#20]
在 PasswordBox 的按键抬起的时候，执行更新后台的密码

https://github.com/GDUT-Drcom/GDUT-Drcom-Dialer/blob/8486cea39861b0bc66a29678b85d60509981be16/Drcom-Dialer/View/MainWindow.xaml#L92-L98

比较官方推荐的方法是通过 PasswordChanged 事件？不知是否采用 PasswordChanged 在这里有坑更换为 KeyUp 事件？

**Comment by jiangming1399** [comment]
这个啊……昨天键盘坏了按不出来PasswordChanged ，所以就临时用了KeyUp
